"""add pinned_position

Revision ID: e23d780921a4
Revises: 25601a8ee757
Create Date: 2026-05-21 23:22:08.603247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23d780921a4'
down_revision: Union[str, Sequence[str], None] = '25601a8ee757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('pinned_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'pinned_position')
    # ### end Alembic commands ###
